# permissions for end users to view managedresourcequota.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedresourcequota-viewer-role
rules:
- apiGroups:
  - k8s-resourcequota-autoscaler.m21r.de
  resources:
  - managedresourcequota
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s-resourcequota-autoscaler.m21r.de
  resources:
  - managedresourcequota/status
  verbs:
  - get
