
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - k8s-resourcequota-autoscaler.m21r.de
  resources:
  - managedresourcequota
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-resourcequota-autoscaler.m21r.de
  resources:
  - managedresourcequota/finalizers
  verbs:
  - update
- apiGroups:
  - k8s-resourcequota-autoscaler.m21r.de
  resources:
  - managedresourcequota/status
  verbs:
  - get
  - patch
  - update
